# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: N:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0.xci
# IP: The module: 'clk_gen_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: N:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0.xci
# IP: The module: 'clk_gen_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: n:/Swaroop_Ka_kachra/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_FPGA-master/OV7670_to_VGA_BRAM/EES_template.srcs/sources_1/bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
