# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ConstrainFiles/ees303.xdc

# Block Designs: bd/vram/vram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vram || ORIG_REF_NAME==vram} -quiet] -quiet

# IP: bd/vram/ip/vram_blk_mem_gen_0_0/vram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vram_blk_mem_gen_0_0 || ORIG_REF_NAME==vram_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/clk_gen/clk_gen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_gen || ORIG_REF_NAME==clk_gen} -quiet] -quiet

# IP: bd/clk_gen/ip/clk_gen_clk_wiz_0_0/clk_gen_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_gen_clk_wiz_0_0 || ORIG_REF_NAME==clk_gen_clk_wiz_0_0} -quiet] -quiet

# XDC: n:/Swaroop_Ka_kachra/Xilinx/MAJOR_PROJECT/VideoProcessing_fps_morefilters/EES_template/EES_template.gen/sources_1/bd/vram/vram_ooc.xdc

# XDC: n:/Swaroop_Ka_kachra/Xilinx/MAJOR_PROJECT/VideoProcessing_fps_morefilters/EES_template/EES_template.gen/sources_1/bd/clk_gen/clk_gen_ooc.xdc
